communicator_wbs:
  ros__parameters:
    debug_mode: False
    response_timeout: 3
    image_quality: 85
    server_url: 'wss://trackvla01.galbot.com/:6667' #'ws://8.140.196.220:8150' 'ws://192.168.10.130:6666' 'ws://192.168.80.19:6666' 'wss://trackvla01.galbot.com/:6667'

logger:
  ros__parameters:
    enable: False
    storage_base_dir: 'recording_trackvla_pp'
